export default {
    isLogin: false,
    inputFind: '',
    inicioPage: 'LogIn',
    productsFiltered: [],
    products: [
      {
        'id': '1',
        'image': 'https://arepa.s3.amazonaws.com/camiseta.png',
        'title': 'Limón',
        'price': 25.12,
        'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      },
      {
        'id': '2',
        'image': 'https://arepa.s3.amazonaws.com/mug.png',
        'title': 'Mandarina',
        'price': 10.23,
        'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      },
      {
        'id': '3',
        'image': 'https://arepa.s3.amazonaws.com/pin.png',
        'title': 'Naranja',
        'price': 4.00,
        'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      },
      {
        'id': '4',
        'image': 'https://arepa.s3.amazonaws.com/stickers1.png',
        'title': 'Melón',
        'price': 22.12,
        'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      },
      {
        'id': '5',
        'image': 'https://arepa.s3.amazonaws.com/stickers2.png',
        'title': 'Sandía',
        'price': 2.78,
        'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      },
      {
        'id': '6',
        'image': 'https://arepa.s3.amazonaws.com/hoodie.png',
        'title': 'Piña',
        'price': 35.12,
        'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      },
      {
        'id': '7',
        'image': 'https://arepa.s3.amazonaws.com/hoodie.png',
        'title': 'Platano',
        'price': 35.24,
        'description': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
      },
    ],
  };